---
title: "221220 - mgm_chile"
output: html_document
date: "2022-12-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Input

```{r message=FALSE, warning=FALSE}
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr, ggplot2, jtools,
       stargazer, qgraph, Matrix, igraph, psychTools, NetworkComparisonTest, bootnet,
       rio, compute.es, foreign, matrixcalc, RColorBrewer, EGAnet, kableExtra, qpdf,
       formattable)
```

```{r}
load(file = here("Input", "Chile_data.RData"))
names(chi_net)
```

## Create objects

```{r}
shortnames <- names(chi_net)

longnames <- c(
  "Inequality belief - wealthy family",
  "Inequality belief - parental education",
  "Inequality belief - education",
  "Inequality belief - work",
  "Inequality belief - people",
  "Inequality belief - politics",
  "Inequality belief - bribes",
  "Inequality belief - race",
  "Inequality belief - religion",
  "Inequality belief - sex",
  "Perception - large income inequality",
  "Perception - tax regressivity",
  "Belief - public redistribution",
  "Belief - market redistribution",
  "Belief - progressive taxation",
  "Judgment - unfair distribution",
  "Judgment - political disinterest in redistribution",
  "Judgment - failure of public redistribution")


stargazer(as.data.frame(chi_net), type = "text", nobs = TRUE)

  
```

# Processing

## Network estimation

### Full network - GGM

```{r}
# Estimate partial correlation network:
cor_chi = cor(chi_net)
ggm_chi <- EBICglasso(S = cor_chi, n = nrow(chi_net))

# Communities
ega_chi = EGA(chi_net)
ega_chi$wc

totalgroup_comm <- list(
 " "=c(1:5),
 " "=c(6:10),
 " "=c(11,13,14,15,17),
 " "=c(12,16,18))
       
totalgroup_cols <- c("#B3CDE3","#FED9A6","#FDDAEC","#CCEBC5","#FFFFCC")
```
### Main plot

```{r}
# Plot network
pdf(file = here("Output", "network.pdf"), paper = "USr", height = 9, width = 12)
ggm_chi_net = qgraph(ggm_chi, 
  layout = "spring", theme = "Borkulo", 
  labels = shortnames,nodeNames = longnames,
  cut = 0.10, 
  #minimum = 0.05, 
  maximum = 1, 
  GLratio=2, mar = c(2.2,2.2,2.2,2.2),
  details = FALSE, vsize=7.0, label.cex=0.8, label.scale=FALSE,
  groups=totalgroup_comm, color=totalgroup_cols,
  legend = TRUE, legend.cex = 0.41, borders = FALSE)
dev.off()

# Plot centrality
centrality(ggm_chi_net)
centrality_graph = centralityPlot(ggm_chi_net, labels = longnames, 
                                      orderBy = "Strength") + 
  geom_vline(xintercept=0, linetype="dotted") +
  scale_x_continuous() +
  theme_nice() + 
  theme(axis.text.y=element_text(hjust=1))

ggsave(here("Output", "centrality.jpg"), centrality_graph,
        height = 4)

#Shortest Path Lenght
SPLMGM <- centrality(ggm_chi, weighted = TRUE)$ShortestPathLengths
SPLMGM <- SPLMGM[upper.tri(SPLMGM)]
#Average shortest path length
ASPL_MGM <- mean(SPLMGM)
```

### Sociodemographic networks - EGA

#### Manual


```{r}
#Fit
EGA_income_0 = EGA(income_0)
EGA_income_1 = EGA(income_1)
EGA_education_0 = EGA(education_0)
EGA_education_1 = EGA(education_1)
EGA_class_0 = EGA(class_0)
EGA_class_1 = EGA(class_1)
```

##### Income

```{r}
#EGA groups
group_income_0 <- list(
 " "=c(2:5),
 " "=c(8:10),
 " "=c(11,13,14,15,17),
 " "=c(1,6,7),
 " "=c(12,16,18))

group_income_1 <- list(
 " "=c(1:5),
 " "=c(6:10),
 " "=c(11:18))

#Network estimation
cor_chi_income_0 = cor(income_0)
cor_chi_income_1 = cor(income_1)

ggm_chi_income_0 <- EBICglasso(S = cor_chi_income_0, n = nrow(income_0))
ggm_chi_income_1 <- EBICglasso(S = cor_chi_income_1, n = nrow(income_1))

#Multiplot
pdf(here("Output", "income.pdf"), 
    height = 5, width = 12)

L<-averageLayout(ggm_chi_income_0,ggm_chi_income_1, layout = "spring")
lmat <- matrix(1:2, 1)
lo <- layout(lmat, width = c(1, 1))

graph_income_0<-qgraph(ggm_chi_income_0, 
  layout = L, theme = "Borkulo", 
  labels = shortnames,
  cut = 0.10, 
  label.scale=FALSE, label.cex = 0.7,
  groups=group_income_0, color=totalgroup_cols,
  legend = FALSE, borders = FALSE, details = FALSE, vsize=7.0,
  title = "Low income")

graph_income_1<-qgraph(ggm_chi_income_1, 
  layout = L, theme = "Borkulo", 
  labels = shortnames,
  cut = 0.10, 
  label.scale=FALSE, label.cex = 0.7,
  groups=group_income_1, color=totalgroup_cols,
  legend = FALSE, borders = FALSE, details = FALSE, vsize=7.0,
  title = "High income")

dev.off()
```

##### Education

```{r}
#EGA groups
group_education_0 <- list(
 " "=c(1:5),
 " "=c(8:10),
 " "=c(11,13,14,15,17),
 " "=c(6,7),
 " "=c(12,16,18))

group_education_1 <- list(
 " "=c(1:5),
 " "=c(6:10),
 " "=c(11:18))

#Network estimation
cor_chi_education_0 = cor(education_0)
cor_chi_education_1 = cor(education_1)

ggm_chi_education_0 <- EBICglasso(S = cor_chi_education_0, n = nrow(education_0))
ggm_chi_education_1 <- EBICglasso(S = cor_chi_education_1, n = nrow(education_1))

#Multiplot
pdf(here("Output", "education.pdf"), 
    height = 5, width = 12)

L<-averageLayout(ggm_chi_education_0,ggm_chi_education_1, layout = "spring")
lmat <- matrix(1:2, 1)
lo <- layout(lmat, width = c(1, 1))

graph_education_0<-qgraph(ggm_chi_education_0, 
  layout = L, theme = "Borkulo", 
  labels = shortnames,
  cut = 0.10, 
  label.scale=FALSE, label.cex = 0.7,
  groups=group_education_0, color=totalgroup_cols,
  legend = FALSE, borders = FALSE, details = FALSE, vsize=7.0,
  title = "Low education")

graph_education_1<-qgraph(ggm_chi_education_1, 
  layout = L, theme = "Borkulo", 
  labels = shortnames,
  cut = 0.10, 
  label.scale=FALSE, label.cex = 0.7,
  groups=group_education_1, color=totalgroup_cols,
  legend = FALSE, borders = FALSE, details = FALSE, vsize=7.0,
  title = "High education")

dev.off()
```

##### Class

```{r}
#EGA groups
group_class_0 <- list(
 " "=c(1:5),
 " "=c(6:10),
 " "=c(11,13,14,15,17),
 " "=c(12,16,18))

group_class_1 <- list(
 " "=c(1,2,5,6,7),
 " "=c(8:10),
 " "=c(11:18),
 " "=c(3:4))

#Network estimation
cor_chi_class_0 = cor(class_0)
cor_chi_class_1 = cor(class_1)

ggm_chi_class_0 <- EBICglasso(S = cor_chi_class_0, n = nrow(class_0))
ggm_chi_class_1 <- EBICglasso(S = cor_chi_class_1, n = nrow(class_1))

pdf(file = here("Output", "network_class.pdf"), paper = "USr", height = 9, width = 12)
ggm_chi_net = qgraph(ggm_chi_class_1, 
  layout = "spring", theme = "Borkulo", 
  labels = shortnames,nodeNames = longnames,
  cut = 0.10, 
  #minimum = 0.05, 
  maximum = 1, 
  GLratio=3,
  details = FALSE, vsize=7.0, label.cex=0.8, label.scale=FALSE,
  groups=totalgroup_comm, color=totalgroup_cols,
  legend = TRUE, legend.cex = 0.3, borders = FALSE)
dev.off()

#Multiplot
pdf(here("Output", "class.pdf"), 
    height = 5, width = 12)

L<-averageLayout(ggm_chi_class_0,ggm_chi_class_1, layout = "spring")
lmat <- matrix(1:2, 1)
lo <- layout(lmat, width = c(1, 1))

graph_class_0<-qgraph(ggm_chi_class_0, 
  layout = L, theme = "Borkulo", 
  labels = shortnames,
  cut = 0.10, 
  label.scale=FALSE, label.cex = 0.7,
  groups=group_class_0, color=totalgroup_cols,
  legend = FALSE, borders = FALSE, details = FALSE, vsize=7.0,
  title = "Low class")

graph_class_1<-qgraph(ggm_chi_class_1, 
  layout = L, theme = "Borkulo", 
  labels = shortnames,
  cut = 0.10, 
  label.scale=FALSE, label.cex = 0.7,
  groups=group_class_1, color=totalgroup_cols,
  legend = FALSE, borders = FALSE, details = FALSE, vsize=7.0,
  title = "High class")

dev.off()
```

##### Multiplot

```{r}
list.files = c(here("Output", "income.pdf"), here("Output", "education.pdf"), 
here("Output", "class.pdf"))

qpdf::pdf_combine(input = list.files,
                  output = here("Output", "multiplot.pdf"))
```

## NCT

```{r}
#Income
NCT_income <- NCT(income_1,income_0, it = 1000,
                test.edges = TRUE, edges = "all", 
                test.centrality = TRUE)

inputNCT_income <- ggm_chi_income_1 - ggm_chi_income_0
inputNCT_income_abs = abs(NCT_income$einv.real) 
sum_income_c = colSums(inputNCT_income_abs)
sum_income = sum(sum_income_c)

#education
NCT_education <- NCT(education_1,education_0, it = 1000,
                test.edges = TRUE, edges = "all", 
                test.centrality = TRUE)

inputNCT_education <- ggm_chi_education_1 - ggm_chi_education_0
inputNCT_education_abs = abs(NCT_education$einv.real) 
sum_education_c = colSums(inputNCT_education_abs)
sum_education = sum(sum_education_c)

#class
NCT_class <- NCT(class_1,class_0, it = 1000,
                test.edges = TRUE, edges = "all", 
                test.centrality = TRUE)

inputNCT_class <- ggm_chi_class_1 - ggm_chi_class_0
inputNCT_class_abs = abs(NCT_class$einv.real) 
sum_class_c = colSums(inputNCT_class_abs)
sum_class = sum(sum_class_c)
```

### Graph edge weights

```{r}
#Graph
graph_edgew = tibble(variable = c("Income", "Education level", "Social class"),
                   dif = c(sum_income, sum_education, sum_class)) %>% 
  arrange(desc(dif)) %>% 
  ggplot(aes(x=reorder(variable, -dif), y = dif, fill=variable)) +
  geom_bar(stat="identity") +
  geom_text(aes(label= formattable::digits(dif, digits = 2)), parse = FALSE, vjust=-0.5, size=3) +
  labs(y = "Differences in edge weights", x="Stratification measures") +
  scale_y_continuous(limits = c(0,7)) +
  theme_nice() +
  theme(legend.position = "none") + 
  scale_fill_brewer(palette = "Pastel1")

ggsave(here("Output", "graph_edgew.jpg"), graph_edgew, height = 6, width = 10)

graph_edgew
```

### Graph centrality

```{r}
#Preparation
cent_income_0 <- centralityTable(ggm_chi_income_0,standardized = FALSE)
cent_income_1 <- centralityTable(ggm_chi_income_1,standardized = FALSE)

cent_education_0 <- centralityTable(ggm_chi_education_0,standardized = FALSE)
cent_education_1 <- centralityTable(ggm_chi_education_1,standardized = FALSE)

cent_class_0 <- centralityTable(ggm_chi_class_0,standardized = FALSE)
cent_class_1 <- centralityTable(ggm_chi_class_1,standardized = FALSE)

## Input graph

#income
c_income_0 = cent_income_0 %>%
  filter(measure=="Strength") %>% 
  select(node, value) %>% 
  cbind(NCT_income$diffcen.pval) %>% 
  rename(pvalue = strength) %>%   
  filter(pvalue<=0.05) %>% 
  rownames_to_column("name") %>% 
  mutate(measure = "Income",
         group = "Low")

c_income_1 = cent_income_1 %>%
  filter(measure=="Strength") %>% 
  select(node, value) %>% 
  cbind(NCT_income$diffcen.pval) %>% 
  rename(pvalue = strength) %>%   
  filter(pvalue<=0.05) %>% 
  rownames_to_column("name") %>% 
  mutate(measure = "Income",
         group = "High")

#education
c_education_0 = cent_education_0 %>%
  filter(measure=="Strength") %>% 
  select(node, value) %>% 
  cbind(NCT_education$diffcen.pval) %>% 
  rename(pvalue = strength) %>%   
  filter(pvalue<=0.05) %>% 
  rownames_to_column("name") %>% 
  mutate(measure = "Education level",
         group = "Low")

c_education_1 = cent_education_1 %>%
  filter(measure=="Strength") %>% 
  select(node, value) %>% 
  cbind(NCT_education$diffcen.pval) %>% 
  rename(pvalue = strength) %>%   
  filter(pvalue<=0.05) %>% 
  rownames_to_column("name") %>% 
  mutate(measure = "Education level",
         group = "High")

#class
c_class_0 = cent_class_0 %>%
  filter(measure=="Strength") %>% 
  select(node, value) %>% 
  cbind(NCT_class$diffcen.pval) %>% 
  rename(pvalue = strength) %>%   
  filter(pvalue<=0.05) %>% 
  rownames_to_column("name") %>% 
  mutate(measure = "Social class",
         group = "Low")

c_class_1 = cent_class_1 %>%
  filter(measure=="Strength") %>% 
  select(node, value) %>% 
  cbind(NCT_class$diffcen.pval) %>% 
  rename(pvalue = strength) %>%   
  filter(pvalue<=0.05) %>% 
  rownames_to_column("name") %>% 
  mutate(measure = "Social class",
         group = "High")

#graph
c_all = rbind(c_income_0, c_income_1,
              c_education_0, c_education_1,
              c_class_0, c_class_1) %>% 
  select(measure, group, everything())

v_factor_levels <- c("Low", "High")

graph_centrality = ggplot(c_all, aes(y=value, x=reorder(name, desc(name)), fill=factor(group, levels = v_factor_levels))) + 
    geom_bar(position="dodge", stat="identity") +
    facet_grid(~measure) +
  coord_flip() +
    labs(y = "Strength", x="", 
         
         caption = "Only differences between high and low groups that are statistically significant",
         ) +
    scale_y_continuous(limits = c(0,1.5)) +
    theme_nice() +
    theme(legend.position = "bottom", plot.caption = element_text(hjust = 0.5)) + 
    scale_fill_brewer(palette = "Pastel1") +
  guides(fill=guide_legend(title="Group"))
  
ggsave(here("Output", "graph_centrality.jpg"), graph_centrality, height = 6, width = 10)

graph_centrality
```

### Graph connectivity

```{r}
#Income 
SPLMGM <- centrality(ggm_chi_income_0)$ShortestPathLengths
SPLMGM <- SPLMGM[upper.tri(SPLMGM)]
ASPL_income0 <- mean(SPLMGM)

SPLMGM <- centrality(ggm_chi_income_1)$ShortestPathLengths
SPLMGM <- SPLMGM[upper.tri(SPLMGM)]
ASPL_income1 <- mean(SPLMGM)

#edu
SPLMGM <- centrality(ggm_chi_education_0)$ShortestPathLengths
SPLMGM <- SPLMGM[upper.tri(SPLMGM)]
ASPL_edu0 <- mean(SPLMGM)

SPLMGM <- centrality(ggm_chi_education_1)$ShortestPathLengths
SPLMGM <- SPLMGM[upper.tri(SPLMGM)]
ASPL_edu1 <- mean(SPLMGM)

#Class
SPLMGM <- centrality(ggm_chi_class_0)$ShortestPathLengths
SPLMGM <- SPLMGM[upper.tri(SPLMGM)]
ASPL_egp0 <- mean(SPLMGM)

SPLMGM <- centrality(ggm_chi_class_1)$ShortestPathLengths
SPLMGM <- SPLMGM[upper.tri(SPLMGM)]
ASPL_egp1 <- mean(SPLMGM)

##Graph
ASPL_table = data.frame(Variable = c("Income", "Income", 
                        "Education level", "Education level", 
                        "Social class","Social class"),
           Level = c("Low", "High",
                     "Low", "High",
                     "Low", "High"),
           ASPL = c(ASPL_income0, ASPL_income1,
                    ASPL_edu0, ASPL_edu1,
                    ASPL_egp0, ASPL_egp1))



# Helper function for string wrapping. 
# Default 20 character target width.
swr = function(string, nwrap=15) {
  paste(strwrap(string, width=nwrap), collapse="\n")
}
swr = Vectorize(swr)

# Create line breaks in Year
ASPL_table$Variable_r = swr(ASPL_table$Variable)

           
graph_connectivity = ggplot(ASPL_table, aes(y=ASPL, x=Level, fill=Variable_r)) + 
    geom_bar(position="dodge", stat="identity") +
    geom_text(aes(label=formattable::digits(ASPL, digits = 2)), vjust=-0.5, size=3) +
    facet_grid(~Variable_r) +
    labs(y = "ASPL", x="", caption = "Differences between high and low groups are not statistically significant for any variable") +
    #scale_y_continuous(limits = c(0,25)) +
    theme_nice() +
    theme(legend.position = "none", plot.caption = element_text(hjust = 0.5)) + 
    scale_fill_brewer(palette = "Pastel1")

ggsave(here("Output", "graph_connectivity.jpg"), graph_connectivity, height = 6, width = 10)

graph_connectivity
```

# Output

## Export heavy objects

```{r}
#communities
saveRDS(CommunityStabTotal, here("Input", "CommunityStabTotal.rds"))
#bootnet
saveRDS(edgeacc, here("Input","edgeacc.rds"))
saveRDS(centstab, here("Input", "centstab.rds"))
```

## Edge weight to excel

```{r}
##only upper triangle without edge weigths 0 for readability
EdgeWeight_Total_half<-upper.triangle(inputGraphMGM)
EdgeWeight_Total_half[EdgeWeight_Total_half == 0] <- NA
EdgeWeightsExcel_half<- list("mgm" = EdgeWeight_Total_half)
write.xlsx(EdgeWeightsExcel_half, "../Output/H1/EdgeWeightsExcel_half.xlsx",
           colWidths = "auto", rowNames = TRUE)
```
