---
title: "221220 - mgm_chile"
output: html_document
date: "2022-12-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Input

```{r message=FALSE, warning=FALSE}
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr, ggplot2, jtools,
       stargazer, IsingFit, qgraph, Matrix, igraph, NetworkComparisonTest, bootnet,
       rio, IsingSampler, compute.es, foreign, mgm, matrixcalc, openxlsx, RColorBrewer)
```

```{r}
CHI <- import("../Input/CHI.csv")
names(CHI)
```

## Create objects

```{r}
shortnames <- c(
"ib_weafam", "ib_edupar", "ib_edu", "ib_work",   "ib_people", "ib_pol",   
"ib_bribes", "ib_race",   "ib_relig",  "ib_sex", 
"ineq_per","ineq_ang", "ineq_jud",  
"red_pub",   "red_pri",   "red_unca",  "red_unsu", 
"tax_bel",  "tax_per",   
"pay_resp",  "pay_educ",  "pay_need",  "pay_merit")

longnames <- c(
  "Inequality belief - wealthy family",
  "Inequality belief - parental education",
  "Inequality belief - education",
  "Inequality belief - work",
  "Inequality belief - people",
  "Inequality belief - politics",
  "Inequality belief - bribes",
  "Inequality belief - race",
  "Inequality belief - religion",
  "Inequality belief - sex",
  
  "Perception - inequality",
  "Judgment - angry for inequality",
  "Judgment - unfairness of income distribution",
  
  "Belief - preference for public redistribution",
  "Belief - preference for private redistribution",
  "Judgment - politicians don't care of redistribution",
  "Judgment - government unsuccess in redistribution",
  
  "Belief - tax progressivity",
  "Perception - low taxes",
  
  "Pay belief - responsability",
  "Pay belief - education",
  "Pay belief - need",
  "Pay belief - merit")
  

type <-c("g","g","g","g","g","g","g","g","g","g","g","g","g",
         "g","g","g","g","g","g","g","g","g","g")


level <-c("1","1","1","1","1","1","1","1","1","1","1","1","1",
          "1","1","1","1","1","1","1","1","1","1")

communityStability <- function(data, type, level, iterations)
{
  
  communityMemberships <- list()
  
  for (i in 1:iterations)
  {
    fitGraph <- mgm(data, type, level, k = 2, verbatim = TRUE)
    iGraph<- graph_from_adjacency_matrix(abs
                                         (fitGraph$pairwise$wadj), "undirected", weighted =
                                           TRUE)
    communityMemberships[[i]] <- cluster_walktrap(iGraph)$membership
  }
  
  communityOverlap <- matrix(NA, length(data), length(data))
  
  for(j in 1:length(data))
  {
    
    overlapPerNode <- matrix(NA, iterations, ncol(communityOverlap))
    
    for(k in 1: iterations)
    {
      overlapPerNode[k,] <- as.numeric(communityMemberships[[k]][j] == communityMemberships[[k]])
    }
    
    communityOverlap[j,] <- apply(overlapPerNode, 2, mean)
  }
  
  diag(communityOverlap) <- 0
  
  return(list(communityMemberships = communityMemberships, communityOverlap = communityOverlap))
  
}

```

# Processing

### Fit on CHI

```{r}
set.seed(1)
mgmFit <- mgm(CHI, type, level, k = 2, binarySign = TRUE)
```
### Communities

```{r}
#function LOAD THE OBJECT down below TO SAVE TIME:
#CommunityStabTotal<-communityStability(CHI, type, level, it=1000)
#load the object instead:
CommunityStabTotal = readRDS(here("Input", "CommunityStabTotal.rds"))
```

```{r}
#vizualise community stability
pdf(file = '../Output/H1/community_stability.pdf',paper = "USr",
    height = 9, width = 12)
qgraph(CommunityStabTotal$communityOverlap, layout = "spring", 
       theme = "Borkulo", labels = shortnames,
       nodeNames = longnames,vsize=4.0,
       edge.labels=FALSE, legend = TRUE, legend.cex = 0.3)
dev.off()

# vizualise detected communities
inputCommDetection_total<-CommunityStabTotal$communityOverlap
inputCommDetection_total[which(inputCommDetection_total <= .90)] <- 0

pdf(file = '../Output/H1/detected_communities.pdf',paper = "USr",
    height = 9, width = 12)
qgraph(inputCommDetection_total, layout = "spring", theme = "Borkulo",
       labels = shortnames, nodeNames = longnames, vsize=4.0,
       edge.labels=FALSE, legend = TRUE, legend.cex = 0.3)
dev.off()

#group variables based on outcome detection community stability so we can assign colors
Totalgroup_comm <- list(
 " "=c(1:5),
 " "=c(6:10),
 " "=c(11,14,15,16,18),
 " "=c(12,13,17,19),
 " "=c(20:23))

# define nice colors
# display.brewer.pal(8,"Pastel1")
# Totalgroup_cols = brewer.pal(8,"Pastel1")
Totalgroup_cols <- c("#FFFFCC","#DECBE4","#FED9A6","#CCEBC5","#FDDAEC")
```
## Plot

```{r}
#enables theme colorblind because we don't need to specify edge.color
inputGraphMGM <- mgmFit$pairwise$wadj
signsGraphMGM <- mgmFit$pairwise$signs
signsGraphMGM[which(is.na(signsGraphMGM))] <- 1
inputGraphMGM <- inputGraphMGM*signsGraphMGM

# refined, no minimum 
pdf(file = '../Output/H1/MGM_nomin.pdf',paper = "USr", height = 9, width = 12)
GraphMGM<-qgraph(inputGraphMGM, 
  layout = "spring", theme = "Borkulo", 
  labels = shortnames, nodeNames = longnames,
  cut = 0.10, maximum = 1, 
  details = FALSE, vsize=6.0,
  groups=Totalgroup_comm, color= Totalgroup_cols,
  legend = TRUE, legend.cex = 0.3, borders = FALSE)
dev.off()

# refined,  minimum = 0.5
pdf(file = '../Output/H1/MGM_min_05.pdf',paper = "USr", height = 9, width = 12)
GraphMGM<-qgraph(inputGraphMGM, 
  layout = "spring", theme = "Borkulo", 
  labels = shortnames,nodeNames = longnames,
  cut = 0.10, minimum = 0.05, maximum = 1, 
  details = FALSE, vsize=6.0, 
  groups=Totalgroup_comm, color= Totalgroup_cols,
  legend = TRUE, legend.cex = 0.3, borders = FALSE)
dev.off()

# refined,  minimum = 0.10
pdf(file = '../Output/H1/MGM_min_10.pdf',paper = "USr", height = 9, width = 12)
GraphMGM<-qgraph(inputGraphMGM, 
  layout = "spring", theme = "Borkulo", 
  labels = shortnames,nodeNames = longnames,
  cut = 0.10, minimum = 0.10, maximum = 1, 
  details = FALSE, vsize=6.0, legend = TRUE,
  groups=Totalgroup_comm, color= Totalgroup_cols,
  legend.cex = 0.3, borders = FALSE)
dev.off()
```

### Centrality estimates

```{r}
#graph with complete labels for centrality plot
GraphMGMCENT<-qgraph(inputGraphMGM, 
  layout = "spring", theme = "colorblind",
  labels = longnames, minimum = 0,
  cut = 0.10, maximum = 1, details = TRUE,
  legend = FALSE)

#centrality Total
centMGM <- centralityTable(GraphMGMCENT,standardized = FALSE)

#CentralityPlot Total
centrality_table = centralityPlot(GraphMGMCENT, include = c("Strength"), scale = "raw",
               orderBy = "Strength") + theme_nice() + theme(axis.text.y=element_text(hjust=1))

ggsave(here("Output", "H1", "Centrality_Table.jpg"), centrality_table)
```

### ASPL

```{r}
#Shortest Path Lenght
SPLMGM <- centrality(GraphMGM, weighted = TRUE)$ShortestPathLengths
SPLMGM <- SPLMGM[upper.tri(SPLMGM)]
#Average shortest path length
ASPL_MGM <- mean(SPLMGM)
```
ASPL (Weighted) m= 19.90601

## Bootstrap

#### Edge accuracy

```{r}
#edge weight accuracy: non parametric bootstrap with 8 cores
#edgeacc =  bootnet(CHI, nBoots = 1000, nCores = 8, 'mgm')

#load the object instead:
edgeacc = readRDS(here("Input", "edgeacc.rds"))

#plot 1
pdf('../Output/H1/robustness/edge_accuracy.pdf', height = 70, width = 50)
plot(edgeacc, labels = longnames, order = "sample")
dev.off()

#Plot 2
pdf('../Output/H1/robustness/edge_accuracy_CI.pdf', height = 70, width = 50)
plot(edgeacc, plot = "interval", split0 = TRUE, order="sample", labels=longnames)
dev.off()

#summary
saummary_edgeacc = summary(edgeacc, statistics = c("edge", "strength"), 
                            perNode = FALSE, rank = FALSE) 
```

#### Centrality stability

```{r}
# case dropping bootstrap
#centstab = bootnet(CHI, nBoots = 1000, 'mgm', type = "case", nCores = 8)

#load the object instead:
centstab = readRDS(here("Input", "centstab.rds"))

#plot 1
pdf('../Output/H1/robustness/Centrality_stability.pdf', height = 70, width = 50)
plot(centstab, "Strength", perNode = TRUE, labels = longnames,
     subsetRange = c(100,50))
dev.off()

#Plot 2
pdf('../Output/H1/robustness/Centrality_stability_CI.pdf', height = 70, width = 50)
plot(centstab, "Strength", CIstyle =  "quantiles")
dev.off()

#CS-coefficient (result should be above 0.25, better if above 0.5)
corstab = corStability(centstab)
```

#### Testing Edge and centrality differences

```{r}
# Test: difference of weight ties 2-3 vs 4-5
differenceTest(edgeacc, 2--3, 3--4, "strength")

# Plot test results for every edge weight in the network
pdf('../Output/H1/robustness/test_edges.pdf', height = 70, width = 50)
plot(edgeacc, "edge", plot = "difference", onlyNonZero = TRUE, order = "sample", 
     labels = T)
dev.off()
```

```{r}
# Test: difference of strength of node 2 vs 3 (if the bootstrapped CI include 0, they do not differ)
differenceTest(edgeacc, 2, 3, "strength")

# Plot test results for every edge weight in the network
pdf('../Output/H1/robustness/test_strenghts.pdf', height = 70, width = 50)
plot(edgeacc, "strength", order = "mean", labels = T)
dev.off()
```


## H1

```{r}
#small world network
CHI_small_core = smallworldness(mgmFit$pairwise$wadj, B = 1000)
CHI_small_core

```
comment: 
- smallworldness > 1 -> small world network
- rnd values > 1 -> small world network
- averagelength_target (Unweighted)


# Output

## Export heavy objects

```{r}
#communities
saveRDS(CommunityStabTotal, here("Input", "CommunityStabTotal.rds"))
#bootnet
saveRDS(edgeacc, here("Input","edgeacc.rds"))
saveRDS(centstab, here("Input", "centstab.rds"))
```

## Edge weight to excel

```{r}
##only upper triangle without edge weigths 0 for readability
EdgeWeight_Total_half<-upper.triangle(inputGraphMGM)
EdgeWeight_Total_half[EdgeWeight_Total_half == 0] <- NA
EdgeWeightsExcel_half<- list("mgm" = EdgeWeight_Total_half)
write.xlsx(EdgeWeightsExcel_half, "../Output/H1/EdgeWeightsExcel_half.xlsx",
           colWidths = "auto", rowNames = TRUE)
```
