---
title: "221220 - Database"
output: html_document
date: "2022-12-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

# Input

```{r}
#Libraries
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr,
       stargazer, purr, conflicted)

#devtools::install_github("DiogoFerrari/occupar")
library(occupar)

```

```{r}
#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")

options(max.print=999999)
options(scipen=999)
```

## ISSP Social Inequality 2019

```{r}
#Load database
issp_2019_original = read_dta(here("Input", "ZA7600_v3-0-0.dta"))  %>% 
  clean_names()

```

# Processing

## Complete database

```{r}
#Select
issp_2019 = issp_2019_original %>% 
  filter(country==152) %>% 
  select(v1:v50, educyrs, cl_inc, isco08, emprel, nsup)

#Rename
issp_2019 = issp_2019 %>% 
  rename(family = v1,
         edupar = v2,
         edu = v3,
         work = v4,
         people = v5,
         connec = v6,
         bribes = v7,
         race = v8,
         relig = v9,
         sex = v10,
         ineq_p = v21,
         ineq_j = v50,
         redis_p = v22,
         redis_m = v24,
         redis_d = v26,
         redis_f = v27,
         prog_b = v28,
         reg_p = v29,
         resp = v44,
         train = v45,
         need = v46,
         merit = v47)

#Reorder
issp_2019 = issp_2019 %>% 
  select(ineq_p,
         reg_p,
         prog_b,
         ineq_j,
         redis_d,
         redis_f,
         family,
         edupar,
         edu,
         work,
         people,
         connec,
         bribes,
         race,
         relig,
         sex,
         redis_p,
         redis_m,
         resp,
         train,
         need,
         merit,
         everything())

```


```{r}
#Missing values and inverting polarity
issp_2019 = issp_2019 %>% 
  mutate(across(ineq_p:merit, ~replace(., .<0 , NA)),
         across(c(educyrs, cl_inc, isco08, emprel, nsup), ~replace(., .<0 , NA)),
         across(family:sex,  ~ 6 - .),
         across(c(ineq_p, redis_p, redis_m, redis_d, prog_b),  ~ 6 - .),
         across(resp:merit,  ~ 6 - .))
         


#Reorder
issp_2019 = issp_2019 %>% 
  select(ineq_p,
         reg_p,
         prog_b,
         ineq_j,
         redis_d,
         redis_f,
         family,
         edupar,
         edu,
         work,
         people,
         connec,
         bribes,
         race,
         relig,
         sex,
         redis_p,
         redis_m,
         resp,
         train,
         need,
         merit,
         everything())
```


## Attitudes towards inequality database

```{r}

#Select and listwise
chi_net = issp_2019 %>% 
  select(ineq_p:merit) %>% 
  na.omit()

names(chi_net)

```

## Networks for NCTs

### Income

```{r}

#Select and listwise
chi_income = issp_2019 %>% 
  select(ineq_p:merit,
         cl_inc) %>% 
  rename(income_h = cl_inc) %>% 
  na.omit()

#Dummy
chi_income = chi_income %>% 
  mutate(income_h = ifelse(income_h<=448000, 0, 1)) #448000

#Split
chi_income = chi_income %>% 
  group_split(income_h, .keep = FALSE)

income_0 = chi_income[[1]]
income_1 = chi_income[[2]]
```


### Education

```{r}

#Select and listwise
chi_education = issp_2019 %>% 
  select(ineq_p:merit,
         educyrs) %>% 
  na.omit()

#Dummy
chi_education = chi_education %>% 
  mutate(education = ifelse(educyrs<=11, 0, 1)) %>% 
  select(-educyrs)
  #11 years (Incomplete secondary) 

#Split
chi_education = chi_education %>% 
  group_split(education, .keep = FALSE)

education_0 = chi_education[[1]]
education_1 = chi_education[[2]]
```


### EGP social class

```{r}

#Select and listwise
chi_class = issp_2019 %>% 
  select(ineq_p:merit,
         isco08, emprel, nsup)

#ISCO08 - Code (isco08_code)
chi_class = chi_class %>% 
  separate(isco08, c("isco08_code", "isco08_label"), remove = FALSE) %>% 
  mutate(isco08_code = as.numeric(paste0(isco08_code)),
         isco08_label = ifelse(is.na(isco08_code), NA, isco08_label))

#Self-employed (self_employed)
chi_class = chi_class %>% 
  mutate(self_employed_ = as.numeric(emprel)) %>% 
  mutate(self_employed = case_when(self_employed_==3 ~ 0,
                               self_employed_>=4 & self_employed_<=7 ~ 1,
                               TRUE ~ NA_real_))

#Number of employees (n_employees)
chi_class = chi_class %>% 
  mutate(n_employees = ifelse(nsup<0, NA, nsup))

#ISCO08 - ISCO88 - EGP
chi_class = chi_class %>% 
  mutate(isco88_code = isco08to88(isco08_code, display.nas = FALSE)) %>% 
  mutate(social_class_3 = isco88toEGP(isco88_code, n.employees=n_employees, self.employed=self_employed, n.classes=3)) 

#Drop IV.c+VII.b  Farm workers 
chi_class = chi_class %>% 
  filter(social_class_3!="IV.c+VII.b  Farm workers")


#Select and listwise
chi_class = chi_class %>% 
  select(ineq_p:merit,
         social_class_3) %>% 
  na.omit()

#Dummy
chi_class = chi_class %>% 
  mutate(social_class_3 = ifelse(
                  social_class_3=="V+VI+VI.a Manual workers", 0, 1)) #V+VI+VI.a Manual workers

#Split
chi_class = chi_class %>% 
  group_split(social_class_3, .keep = FALSE)

class_0 = chi_class[[1]]
class_1 = chi_class[[2]]


```

## Summary

```{r}
#chi_net
summary_chi_net  = chi_net %>% 
  skim() %>% 
  as.data.frame()

stargazer(as.data.frame(chi_net), type = "text", nobs = TRUE)
```
# Output

```{r}

#Save objects
save(chi_net,
     income_0, income_1,
     education_0, education_1,
     class_0, class_1,
     file = here("Input", "Chile_data.RData"))

```


